import React, { useEffect } from 'react'
import './Tradingview.css'


function Tradingview() {

    // api_url_btc = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
    // parameters = {
    // 'id':'1',   
    // 'convert':'USD'
    // }
    // headers = {
    // 'Accepts': 'application/json',
    

    // 'X-CMC_PRO_API_KEY': '439a6f18-ad33-459b-84e9-16b5f51c81bc',

    // }


    // api_url_eth = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
    // parameters = {
    // 'id':'1027',   
    // 'convert':'USD'
    // }
    // headers = {
    // 'Accepts': 'application/json',
    

    // 'X-CMC_PRO_API_KEY': '439a6f18-ad33-459b-84e9-16b5f51c81bc',

    // }

    useEffect(() => {
        
        // axios.get("api_url")
    }, [])


    return (
        <div>
            <marquee class="js-marquee" style={{marginRight: "20px", float: "left", color:"#fff"}}>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/btc.png" style={{marginRight: "5px KhtmlBoxAlign", position:"relative", top:"-2px"}} /><span class="for" style={{paddingRight: "10px"}}>Bitcoin<span class="small">[BTC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-859 price">$34,633.00</span><span style={{paddingRight: "15px"}} class="smaller delta-859 price up">+50.78%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/eth.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Ethereum<span class="small">[ETH]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-145 price">$1,140.67</span><span style={{paddingRight: "15px"}} class="smaller delta-145 price up">+73.27%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/ltc.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Litecoin<span class="small">[LTC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-359 price">$166.52</span><span style={{paddingRight: "15px"}} class="smaller delta-359 price up">+65.05%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/xrp.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>XRP<span class="small">[XRP]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-619 price">$0.232</span><span style={{paddingRight: "15px"}} class="smaller delta-619 price down">-60.24%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/ada.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}><span class="small">[ADA]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-122882 price">$ 0.32</span><span style={{paddingRight: "15px"}} class="smaller delta-122882 price up">+87.43%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/bch.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Bitcoin Cash<span class="small">[BCH]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-157 price">$435.86</span><span style={{paddingRight: "15px"}} class="smaller delta-157 price up">+35.65%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/xlm.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Stellar<span class="small">[XLM]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-489 price">$0.342</span><span style={{paddingRight: "15px"}} class="smaller delta-489 price up">+79.26%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/bnb.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Binance Coin<span class="small">[BNB]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1209 price">$42.17</span><span style={{paddingRight: "15px"}} class="smaller delta-1209 price up">+35.67%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/link.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>ChainLink<span class="small">[LINK]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-7618 price">$16.47</span><span style={{paddingRight: "15px"}} class="smaller delta-7618 price up">+17.99%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/usdt.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Tether<span class="small">[USDT]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-637 price">$1.003</span><span style={{paddingRight: "15px"}} class="smaller delta-637 price up">+0.26%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/bchsv.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Bitcoin SV<span class="small">[BSV]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1510485 price">$ 176.65</span><span style={{paddingRight: "15px"}} class="smaller delta-1510485 price down">-3.51%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/eos.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>EOS<span class="small">[EOS]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-585 price">$3.247</span><span style={{paddingRight: "15px"}} class="smaller delta-585 price up">+3.21%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/xmr.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}></span>Monero<span class="small">[XMR]</span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-6 price">$138.94</span><span style={{paddingRight: "15px"}} class="smaller delta-6 price down">-12.40%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/xem.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>NEM<span class="small">[XEM]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-544 price">$0.257</span><span style={{paddingRight: "15px"}} class="smaller delta-544 price down">-3.72%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/snx.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Synthetix<span class="small">[SNX]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1510573 price">$12.64</span><span style={{paddingRight: "15px"}} class="smaller delta-1510573 price up">+136.25%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/trx.png" style={{margiRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>TRON<span class="small">[TRX]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-8550 price">$0.0303</span><span style={{paddingRight: "15px"}} class="smaller delta-8550 price down">-4.46%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/theta.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Theta Token<span class="small">[THETA]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-433804 price">$2.244</span><span style={{paddingRight: "15px"}} class="smaller delta-433804 price up">+156.19%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/xtz.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Tezos<span class="small">[XTZ]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-986 price">$2.659</span><span style={{paddingRight: "15px"}} class="smaller delta-986 price up">+11.07%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/vet.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>VeChain<span class="small">[VET]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1248415 price">$0.0310</span><span style={{paddingRight: "15px"}} class="smaller delta-1248415 price up">+80.63%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/neo.png" style={{marginRight: "5px", position:"relative",top:"-2px"}} /><span style={{paddingRight: "10px"}}>NEO<span class="small">[NEO]</span> </span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1015 price">$19.19</span><span style={{paddingRight: "15px"}} class="smaller delta-1015 price up">+5.01%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/doge.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}><span class="small">[DOGE]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-280 price">$0.0101</span><span style={{paddingRight: "15px"}} class="smaller delta-280 price up">+182.70%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/atom2.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}> Cosmos<span class="small">[ATOM]</span></span><span style={{paddingRight: "8px",fontWeight: "600", fontSize: "14px"}} class="avgprice-392 price">$6.367</span><span style={{paddingRight: "15px"}} class="smaller delta-392 price up">+13.74%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/ht.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Huobi-Token<span class="small">[HT]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-503637 price">$4.942</span><span style={{paddingRight: "15px"}} class="smaller delta-503637 price up">+20.89%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/iot.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>IOTA<span class="small">[IOT]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1026 price">$0.392</span><span style={{paddingRight: "15px"}} class="smaller delta-1026 price up">+18.42%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/cro.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Crypto.com Chain<span class="small">[CRO]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1510617 price">$0.0712</span><span style={{paddingRight: "15px"}} class="smaller delta-1510617 price up">+2.76%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/dash.png" style={{marginRight: "5px", position:"relative", top:"-2p;"}} /><span style={{paddingRight: "10px"}}>Dash<span class="small">[DASH]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1188 price">$92.30</span><span style={{paddingRight: "15px"}} class="smaller delta-1188 price down">-12.85%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/etc.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Ethereum Classic<span class="small">[ETC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-451 price">$7.469</span><span style={{paddingRight: "15px"}} class="smaller delta-451 price up">+12.28%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/mkr.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Maker<span class="small">[MKR]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-864 price">$849.99</span><span style={{paddingRight: "15px"}} class="smaller delta-864 price up">+53.79%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/zil.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Zilliqa<span class="small">[ZIL]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-466354 price">$0.0821</span><span style={{paddingRight: "15px"}} class="smaller delta-466354 price up">+112.73%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/lend.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>EthLend<span class="small">[LEND]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-237537 price">$ 0.61</span><span style={{paddingRight: "15px"}} class="smaller delta-237537 price up">+29.25%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/zec.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-66 price">$62.28</span><span style={{paddingRight: "15px"}} class="smaller delta-66 price down">-17.01%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/waves.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Waves<span class="small">[WAVES]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1250 price">$5.876</span><span style={{paddingRight: "15px"}} class="smaller delta-1250 price down">-29.86%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/dcr.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Decred<span class="small">[DCR]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-96 price">$49.64</span><span style={{paddingRight: "15px"}} class="smaller delta-96 price up">+63.70%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/omg.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>OmiseGo<span class="small">[OMG]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-135 price">$3.785</span><span style={{paddingRight: "15px"}} class="smaller delta-135 price up">+11.55%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/usdc.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>USCoin<span class="small">[USDC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-648685 price">$ 1.00</span><span style={{paddingRight: "15px"}} class="smaller delta-648685 price down">-0.16%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/okb.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>OKB Token<span class="small">[OKB]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-735538 price">$7.444</span><span style={{paddingRight: "15px"}} class="smaller delta-735538 price up">+26.89%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/dgd.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Digix DAO<span class="small">[DGD]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-300 price">$217.68</span><span style={{paddingRight: "15px"}} class="smaller delta-300 price up">+71.50%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/lrc.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Loopring<span class="small">[LRC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-122808 price">$0.398</span><span style={{paddingRight: "15px"}} class="smaller delta-122808 price up">+125.57%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/dgb.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>DigiByte<span class="small">[DGB]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-61 price">$0.0281</span><span style={{paddingRight: "15px"}} class="smaller delta-61 price up">+26.62%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/bat.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Basic-Attention-Token<span class="small">[BAT]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1088 price">$0.251</span><span style={{paddingRight: "15px"}} class="smaller delta-1088 price up">+8.78%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/ont.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Ontology<span class="small">[ONT]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-633095 price">$0.552</span><span style={{paddingRight: "15px"}} class="smaller delta-633095 price up">+0.80%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/nexo.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Nexo<span class="small">[NEXO]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-859347 price">$0.609</span><span style={{paddingRight: "15px"}} class="smaller delta-859347 price down">-12.61%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/algo.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Algorand<span class="small">[ALGO]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1511107 price">$0.513</span><span style={{paddingRight: "15px"}} class="smaller delta-1511107 price up">+51.25%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/icx.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>ICON<span class="small">[ICX]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-122908 price">$0.629</span><span style={{paddingRight: "15px"}} class="smaller delta-122908 price up">+50.16%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/zrx.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>0x<span class="small">[ZRX]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-386 price">$0.494</span><span style={{paddingRight: "15px"}} class="smaller delta-386 price up">+17.98%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/qtum.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>QTUM<span class="small">[QTUM]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1222 price down">$2.895</span><span style={{paddingRight: "15px"}} class="smaller delta-1222 price up">+3.92%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/fxc.png" style={{marginRight: "5px",position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Flexacoin<span class="small">[FXC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1511075 price">$0.0104</span><span style={{paddingRight: "15px"}} class="smaller delta-1511075 price up">+78.11%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/edc4.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>EDCBlockchain<span class= "small">[EDC]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1511019 price">$0.0520</span><span style={{paddingRight: "15px"}} class="smaller delta-1511019 price down">-29.68%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/nano.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Nano<span class="small">[NANO]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-1187 price">$1.808</span><span style={{paddingRight: "15px"}} class="smaller delta-1187 price up">+52.96%</span>
                <img alt="coin data" class="coin-thumb-xsmall" src="coin/ren.png" style={{marginRight: "5px", position:"relative", top:"-2px"}} /><span style={{paddingRight: "10px"}}>Republic Protocol<span class="small">[REN]</span></span><span style={{paddingRight: "8px", fontWeight: "600", fontSize: "14px"}} class="avgprice-575371 price">$ 0.36</span><span style={{paddingRight: "15px"}} class="smaller delta-575371 price up">+20.21%</span>
            </marquee>
        </div>
    )
}

export default Tradingview
